document.getElementById('b0').style.display="flex";
document.getElementById('b1').style.display="none";
document.getElementById('b2').style.display="none";
document.getElementById('b3').style.display="none";
document.getElementById('b4').style.display="none";
document.getElementById('b5').style.display="none";
document.getElementById('b6').style.display="none";
document.getElementById('b7').style.display="none";
document.getElementById('b8').style.display="none";
function Mostrar0(){
document.getElementById('b0').style.display="flex";
document.getElementById('b1').style.display="none";
document.getElementById('b2').style.display="none";
document.getElementById('b3').style.display="none";
document.getElementById('b4').style.display="none";
document.getElementById('b5').style.display="none";
document.getElementById('b6').style.display="none";
document.getElementById('b7').style.display="none";
document.getElementById('b8').style.display="none";
}
function Mostrar1(){
document.getElementById('b0').style.display="none";
document.getElementById('b1').style.display="flex";
document.getElementById('b2').style.display="none";
document.getElementById('b3').style.display="none";
document.getElementById('b4').style.display="none";
document.getElementById('b5').style.display="none";
document.getElementById('b6').style.display="none";
document.getElementById('b7').style.display="none";
document.getElementById('b8').style.display="none";
}
function Mostrar2(){
document.getElementById('b0').style.display="none";
document.getElementById('b1').style.display="none";
document.getElementById('b2').style.display="flex";
document.getElementById('b3').style.display="none";
document.getElementById('b4').style.display="nono";
document.getElementById('b5').style.display="none";
document.getElementById('b6').style.display="none";
document.getElementById('b7').style.display="none";
document.getElementById('b8').style.display="none";
}
function Mostrar3(){
document.getElementById('b0').style.display="none";
document.getElementById('b1').style.display="none";
document.getElementById('b2').style.display="none";
document.getElementById('b3').style.display="flex";
document.getElementById('b4').style.display="none";
document.getElementById('b5').style.display="none";
document.getElementById('b6').style.display="none";
document.getElementById('b7').style.display="none";
document.getElementById('b8').style.display="none";
}
function Mostrar4(){
document.getElementById('b0').style.display="none";
document.getElementById('b1').style.display="none";
document.getElementById('b2').style.display="none";
document.getElementById('b3').style.display="none";
document.getElementById('b4').style.display="flex";
document.getElementById('b5').style.display="none";
document.getElementById('b6').style.display="none";
document.getElementById('b7').style.display="none";
document.getElementById('b8').style.display="none";
}
function Mostrar5(){
document.getElementById('b0').style.display="none";
document.getElementById('b1').style.display="none";
document.getElementById('b2').style.display="none";
document.getElementById('b3').style.display="none";
document.getElementById('b4').style.display="none";
document.getElementById('b5').style.display="flex";
document.getElementById('b6').style.display="none";
document.getElementById('b7').style.display="none";
document.getElementById('b8').style.display="none";
}
function Mostrar6(){
document.getElementById('b0').style.display="none";
document.getElementById('b1').style.display="none";
document.getElementById('b2').style.display="none";
document.getElementById('b3').style.display="none";
document.getElementById('b4').style.display="none";
document.getElementById('b5').style.display="none";
document.getElementById('b6').style.display="flex";
document.getElementById('b7').style.display="none";
document.getElementById('b8').style.display="none";
}
function Mostrar7(){
document.getElementById('b0').style.display="none";
document.getElementById('b1').style.display="none";
document.getElementById('b2').style.display="none";
document.getElementById('b3').style.display="none";
document.getElementById('b4').style.display="none";
document.getElementById('b5').style.display="none";
document.getElementById('b6').style.display="none";
document.getElementById('b7').style.display="flex";
document.getElementById('b8').style.display="none";
}
function Mostrar8(){
document.getElementById('b0').style.display="none";
document.getElementById('b1').style.display="none";
document.getElementById('b2').style.display="none";
document.getElementById('b3').style.display="none";
document.getElementById('b4').style.display="none";
document.getElementById('b5').style.display="none";
document.getElementById('b6').style.display="none";
document.getElementById('b7').style.display="none";
document.getElementById('b8').style.display="flex";
}